name: Xygeni Bot
on:
  workflow_dispatch:  # Allows manual triggering
  # no schedule triggers

permissions:
  contents: write
  pull-requests: write

jobs:
  xygeni-bot:
    name: Xygeni Bot
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Shallow clones are not required 

      - name: maven-settings
        uses: s4u/maven-settings-action@v2
        with:
          servers: '[{"id": "github", "username": "dummy", "password": "${GITHUB_TOKEN_REF}"}]'
          githubServer: false
        env:
          GITHUB_TOKEN_REF: ${{ secrets.GH_PAT_FOR_ACTIONS_TOKEN }}

      - name: Xygeni-Scanner
        uses: xygeni/xygeni-action@4e94e5ea737f5ebfedac8b1a5b75d8c60c21932d
        id: Xygeni-Scanner
        with:
          command: deps --auto-remediate --format none
          xygeni_url: https://apidemo.xygeni.io/deps-doctor-service
          token: ${{ secrets.XYGENI_TOKEN }}
          gh_token: ${{ secrets.GITHUB_TOKEN }} 

